import{textColor as t,multiply as i,brighten as s,alphaBlend as e,makeHsv as a}from"../../libraries/common/cs/text-color.esm.js"
export default async function({addon:h}){const r=await h.tab.traps.getPaper(),f=()=>t(h.settings.get("primary"),i(h.settings.get("primary"),{r:.66,g:.76,b:.8}),s(h.settings.get("primary"),{r:.75,g:.75,b:.75}),60),c=()=>h.self.disabled||!h.settings.get("affectPaper"),n=t=>"rgb"===t.type&&0===t.red&&.615686274509804===t.green&&.9254901960784314===t.blue,o=r.Item.prototype.draw
r.Item.prototype.draw=function(...e){return c()?(this.saColorChanged=0,this.saOldFillColor&&(this.fillColor=this.saOldFillColor),this.saOldStrokeColor&&(this.strokeColor=this.saOldStrokeColor),o.apply(this,e)):(this.saColorChanged||(this.data.isRectSelect?(this.saOldStrokeColor=this.strokeColor,this.saColorChanged=1,this.strokeColor=t(h.settings.get("accent"),i(h.settings.get("accent"),{r:.67,g:.67,b:.67}),s(h.settings.get("accent"),{r:.67,g:.67,b:.67}))):(this.parent?.data.isGuideLayer||this.parent?.parent?.data.isGuideLayer)&&(this.data.origItem||this.parent?.selectionAnchor===this?(this.saOldStrokeColor=this.parent?.selectionAnchor===this?null:this.strokeColor,this.saColorChanged=1,this.strokeColor=h.settings.get("highlightText")):this.strokeColor&&n(this.strokeColor)&&(this.saOldStrokeColor=this.strokeColor,this.saColorChanged=1,this.strokeColor=f()),this.fillColor&&n(this.fillColor)&&(this.saOldFillColor=this.fillColor,this.saColorChanged=1,this.fillColor=h.settings.get("highlightText")))),o.apply(this,e))},r.Item.prototype.getSelectedColor=()=>c()?null:new r.Color(f())
const l=()=>{if(!r.project)return
let s,n,o,l,g,d
c()?(s="#ffffff",n="#ecf1f9",o="#d9e3f2",l="#4280d7",g="#ffffff",d="#000000"):(s=h.settings.get("accent"),n=e(h.settings.get("accent"),i(h.settings.get("primary"),{a:.1})),o=t(h.settings.get("accent"),e(h.settings.get("accent"),i(a(h.settings.get("primary"),1,.67),{a:.15})),e(h.settings.get("accent"),i(a(h.settings.get("primary"),.5,1),{a:.15})),112),l=f(),g=t(h.settings.get("accent"),"#ffffff","#000000"),d=t(h.settings.get("accent"),"#000000","#ffffff"))
for(let t of r.project.layers)if(t.data.isBackgroundGuideLayer){t.vectorBackground._children[0].fillColor=n,t.vectorBackground._children[1]._children[0].fillColor=s,t.vectorBackground._children[1]._children[1].fillColor=o,t.bitmapBackground._children[0].fillColor=s,t.bitmapBackground._children[1].fillColor=o
for(let i=0;3>i;i++)t._children[2]._children[i].strokeColor=g
for(let i=3;6>i;i++)t._children[2]._children[i].strokeColor=d}else if(t.data.isOutlineLayer)t._children[0].strokeColor=s,t._children[1].strokeColor=l
else if(t.data.isDragCrosshairLayer){for(let i=0;3>i;i++)t.dragCrosshair._children[i].strokeColor=g
for(let i=3;6>i;i++)t.dragCrosshair._children[i].strokeColor=d}}
for(h.settings.addEventListener("change",l),h.self.addEventListener("disabled",l),h.self.addEventListener("reenabled",l);;)await h.tab.waitForElement("[class^=paper-canvas_paper-canvas_]",{markAsSeen:1,reduxEvents:["scratch-gui/navigation/ACTIVATE_TAB","scratch-gui/mode/SET_PLAYER","fontsLoaded/SET_FONTS_LOADED","scratch-gui/locales/SELECT_LOCALE","scratch-gui/targets/UPDATE_TARGET_LIST"],reduxCondition(t){return 1===t.scratchGui.editorTab.activeTabIndex&&!t.scratchGui.mode.isPlayerOnly}}),l()}