async function o(o,t,i,e,{yProvider:s}={}){let r,d
const n=s
for(;;){const c=await o.tab.waitForElement(i,{markAsSeen:1,reduxCondition(o){return o.scratchGui?o.scratchGui.mode.isPlayerOnly:1}}),l=(s=n&&c.closest(n))||window
r&&d&&d.removeEventListener("scroll",r,{passive:1}),c.style.display="none",d=l,r=()=>{const o=s?s.scrollTop+s.clientHeight:window.scrollY+window.innerHeight
"string"==typeof e&&(window.location.pathname.split("/")[3]||"")!==e||o<c.closest(t).offsetHeight-500||c&&c.click()},l.addEventListener("scroll",r,{passive:1})}}export default async function({addon:t}){"users"===window.location.pathname.split("/")[1]&&t.settings.get("profileCommentScroll")&&o(t,"#content","[data-control=load-more]")
const i="studios"===window.location.pathname.split("/")[1],e=i&&t.settings.get("studioScroll")
if("projects"===window.location.pathname.split("/")[1]&&t.settings.get("projectScroll")||e){const i=e?".studio-compose-container .load-more-button":"div.comments-container > div.flex-row.comments-list > button",s=()=>o(t,"#view",i,e?"comments":null)
if(location.hash.startsWith("#comments-")){const o=t=>{t.target.closest(i)&&(document.removeEventListener("click",o,1),s())}
document.addEventListener("click",o,1)}else s()}if("messages"===window.location.pathname.split("/")[1]&&t.settings.get("messageScroll")&&o(t,"#view","#view > div > div.messages-details.inner > section.messages-social > button"),i&&t.settings.get("studioProjectScroll")&&o(t,"#view",".studio-projects-grid .studio-grid-load-more > button",""),i&&t.settings.get("studioBrowseProjectScroll")&&o(t,".user-projects-modal-grid",".user-projects-modal:not(.sa-followers-main) .user-projects-modal-grid .studio-grid-load-more > button","",{yProvider:".user-projects-modal-content"}),i&&t.settings.get("studioCuratorScroll")&&o(t,"#view","div > .studio-members:last-child .studio-grid-load-more > button","curators"),i&&t.settings.get("studioActivityScroll")&&o(t,"#view",".studio-activity .studio-grid-load-more > button","activity"),i&&t.tab.redux.state){let o=0,i=0,e=0
t.tab.redux.initialize(),t.tab.redux.addEventListener("statechanged",(t=>{switch(t.detail.action.type){case"projects_APPEND":return void(o=0)
case"curators_APPEND":return void(i=0)
case"activity_APPEND":return void(e=0)}})),document.body.addEventListener("click",(s=>{if(s.target.closest("button.button"))return s.target.closest(".studio-projects-grid .studio-grid-load-more > button")?(o&&s.stopPropagation(),void(o=1)):s.target.closest("div > .studio-members:last-child .studio-grid-load-more > button")?(i&&s.stopPropagation(),void(i=1)):s.target.closest(".studio-activity .studio-grid-load-more > button")?(e&&s.stopPropagation(),void(e=1)):void(s.target.closest(".user-projects-modal:not(.sa-followers-main) .user-projects-modal-grid .studio-grid-load-more > button")&&t.tab.redux.state?.["user-projects"].loading&&s.stopPropagation())}),{capture:1})}}