export default async function({addon:t}){const e=Object.assign(Object.create(null),{upload:{index:0,tooltip:"gui.spriteSelector.addSpriteFromFile"},surprise:{index:1,tooltip:"gui.spriteSelector.addSpriteFromSurprise"},paint:{index:2,tooltip:"gui.spriteSelector.addSpriteFromPaint"},library:{index:3,tooltip:"gui.spriteSelector.addSpriteFromLibrary"}}),o=Object.assign(Object.create(null),{upload:{index:0,tooltip:"gui.stageSelector.addBackdropFromFile"},surprise:{index:1,tooltip:"gui.stageSelector.addBackdropFromSurprise"},paint:{index:2,tooltip:"gui.stageSelector.addBackdropFromPaint"},library:{index:3,tooltip:"gui.spriteSelector.addBackdropFromLibrary"}}),i=Object.assign(Object.create(null),{upload:{index:0,tooltip:"gui.costumeTab.addFileCostume"},surprise:{index:1,tooltip:"gui.costumeTab.addSurpriseCostume"},paint:{index:2,tooltip:"gui.costumeTab.addBlankCostume"},library:{index:3,tooltip:"gui.costumeTab.addCostumeFromLibrary"}}),r=Object.assign(Object.create(null),{upload:{index:0,tooltip:"gui.soundTab.fileUploadSound"},surprise:{index:1,tooltip:"gui.soundTab.surpriseSound"},record:{index:2,tooltip:"gui.soundTab.recordSound"},library:{index:3,tooltip:"gui.soundTab.addSoundFromLibrary"}}),a=e=>t.self.disabled?"library":t.settings.get(e),d=d=>d.closest("[class*=asset-panel_wrapper_]")?2===t.tab.redux.state.scratchGui.editorTab.activeTabIndex?r[a("sound")]||r.library:i[a("costume")]||i.library:d.closest('[class*="target-pane_stage-selector-wrapper"]')?o[a("backdrop")]||o.library:e[a("sprite")]||e.library
document.body.addEventListener("click",(e=>{if(t.self.disabled)return
const o=e.target.closest('[class*="action-menu_main-button_"]')
if(!o)return
e.stopPropagation()
const i=o.parentElement.querySelector('[class*="action-menu_more-buttons_"]').children,{index:r}=d(o)
i[i.length-(4-r)].querySelector("button").click()}),{bubble:1}),document.body.addEventListener("mouseover",(e=>{const o=e.target.closest('[class*="action-menu_main-button_"]')
if(!o)return
const i=o.parentElement.querySelector(".__react_component_tooltip"),{tooltip:r}=d(o),a=t.tab.redux.state.locales.messages[r]
a&&i.textContent!==a&&(i.textContent=a,setTimeout((()=>{i.textContent=a,o.dispatchEvent(new Event("mouseenter"))})))}),{bubble:1})}