import e from"../../libraries/thirdparty/cs/fuse.esm.min.js"
import t from"./fuse-options.js"
export default async function({addon:a,msg:o}){async function n(){window.location.href.includes("galleries")?l.setAttribute("placeholder",o("studio-placeholder")):window.location.href.includes("trash")?l.setAttribute("placeholder",o("trash-placeholder")):l.setAttribute("placeholder",o("project-placeholder")),await a.tab.waitForElement(".dropdown.button.grey.small"),c.before(d),w=await a.tab.waitForElement(".media-list > .media-list"),document.querySelector('.dropdown-menu.radio-style > [data-control="sort"]').addEventListener("click",(()=>{j=1,b=[]})),m=await a.tab.waitForElement('[data-control="load-more"]'),m.addEventListener("click",(()=>{r()})),l.focus()}async function s(){if(await w,g)if(""===l.value)c.querySelector("span span").innerText=h,f.remove(),y.remove(),m.style.display="",b.forEach((e=>{e.element.remove(),w.appendChild(e.element)}))
else{c.querySelector("span span").innerText=o("search-by")
const e=g.search(l.value).sort(((e,t)=>.1>e.score^.1>t.score?.1>e.score?-1:1:0))
b.forEach((e=>{e.element.remove()})),e.forEach((e=>{w.appendChild(e.item.element)}))}}function i(){w&&""!==l.value&&!p&&(0===w.querySelectorAll("li").length?r():u?(f.innerText=o("end-header"),y.innerText=o("end-tip")):(f.innerText=o("load-more-header"),y.innerText=o("load-more-tip"),m.style.display=""),w.appendChild(f),w.appendChild(y))}async function r(){if(""!==l.value&&!p){p=1
const e=w.querySelectorAll("li").length
let t
m.style.display="none",m.click(),j++,f.innerText=o("progress-header"),y.innerText=o("progress-tip",{number:40*(j-2)})
let a,n="",i=document.querySelectorAll(".dropdown.button.grey.small")
window.location.href.includes("galleries")?(i=i[1].querySelector("li.selected"),t="galleries/all"):(i=i[0].querySelector("li.selected"),t=window.location.href.includes("trash")?"trashed/all":window.location.href.includes("unshared")?"projects/notshared":window.location.href.includes("shared")?"projects/shared":"projects/all"),a=i.getAttribute("data-ascsort")||"",n=i.getAttribute("data-descsort")||"",t=`https://scratch.mit.edu/site-api/${t}/?page=${j}&ascsort=${a}&descsort=${n}`,await fetch(t).then((async t=>{t.ok?(await b[e],await s().then((()=>{w.querySelectorAll("li").length!==e&&(p=0)}))):(p=0,u=1)})).catch((()=>{p=0})),p?setTimeout((()=>{p=0,r()}),500):w&&(w.querySelectorAll("li").length!==e?(f.innerText=o("load-more-header"),y.innerText=o("load-more-tip"),m.style.display=""):0!==w.querySelectorAll("li").length?(f.innerText=o("end-header"),y.innerText=o("end-tip")):(f.innerText=o("no-results-header"),y.innerText=o("no-results-tip")),f.remove(),y.remove(),w.appendChild(f),w.appendChild(y))}}let d,l,c,m,p,u,h,w,f,y,g,b=[],j=1
!async function(){d=document.createElement("form"),d.id="search-my-stuff-form",l=document.createElement("input"),l.id="search-my-stuff-input",l.setAttribute("type","text"),d.appendChild(l),c=await a.tab.waitForElement(".dropdown.button.grey.small"),h=c.querySelector("span").innerText,f=document.createElement("h2"),f.id="search-my-stuff-header",y=document.createElement("span"),y.id="search-my-stuff-tip"}(),n(),async function(){for(;;){const o=await a.tab.waitForElement(".media-list > li",{markAsSeen:1})
b.push({name:o.querySelector(".media-info-item.title > a").innerText,element:o}),g=new e(b,t),""!==l.value&&s().then(i)}}(),document.addEventListener("keypress",(e=>{e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.ctrlKey||e.altKey||e.metaKey||!/^\w$/.test(e.key)||l.focus()})),d.addEventListener("keydown",(e=>{(e.ctrlKey||e.metaKey)&&"Enter"===e.key&&""!==l.value&&w.childNodes.length>0&&(window.location.href=w.childNodes[0].querySelector("a").href)})),d.addEventListener("submit",(e=>{e.preventDefault()})),l.addEventListener("input",(()=>{s().then(i)})),a.self.addEventListener("disabled",(()=>{d.remove()})),a.self.addEventListener("reenabled",n),a.tab.addEventListener("urlChange",(async()=>{b=[],j=1,u=0,w=void 0,await a.tab.waitForElement(".media-list > li"),c=document.querySelector(".dropdown.button.grey.small"),n(),h=c.querySelector("span").innerText}))}