import t from"./Trap.js"
import e from"./ReduxHandler.js"
import r from"../common/Listenable.js"
import o from"../../libraries/common/cs/data-url-to-blob.js"
import*as n from"./blocks.js"
import{addContextMenu as s}from"./contextmenu.js"
import*as a from"./modal.js"
const u=[],i=["editor-devtools","block-switching","blocks2image","swap-local-global"]
let l=0
export default class c extends r{constructor(r){super(),this._addonId=r.id,this.traps=new t(this),this.redux=new e,this._waitForElementSet=new WeakSet}get clientVersion(){return this._clientVersion||(this._clientVersion=document.querySelector("meta[name='format-detection']")?"scratch-www":document.querySelector("script[type='text/javascript']")?"scratchr2":null),this._clientVersion}addBlock(t,e){return n.init(this),n.addBlock(t,e)}removeBlock(t){return n.removeBlock(t)}setCustomBlockColor(t){return n.setCustomBlockColor(t)}getCustomBlockColor(){return n.color}getCustomBlock(t){return n.getCustomBlock(t)}loadScript(t){return new Promise(((e,r)=>{if(scratchAddons.loadedScripts[t]){const o=scratchAddons.loadedScripts[t]
o.loaded?e():null===o.error?(o.script.addEventListener("load",(()=>{e()})),o.script.addEventListener("error",(({error:e})=>{r(`Failed to load script from ${t} - ${e}`)}))):r(`Failed to load script from ${t} - ${o.error}`)}else{const o=document.createElement("script")
o.src=t
const n=scratchAddons.loadedScripts[t]={script:o,loaded:0,error:null}
document.head.appendChild(o),o.addEventListener("load",(()=>{n.loaded=1,e()})),o.addEventListener("error",(({error:e})=>{n.error=e,r(`Failed to load script from ${t} - ${e}`)}))}}))}waitForElement(t,e={}){const r=!!e.markAsSeen
if(!e.condition||e.condition()){const o=document.querySelectorAll(t)
for(const t of o)if(!this._waitForElementSet.has(t)&&(!e.elementCondition||e.elementCondition(t)))return r&&this._waitForElementSet.add(t),Promise.resolve(t)}const{reduxCondition:o,condition:n}=e
let s,a=()=>n&&!n()||this.redux.state&&o&&!o(this.redux.state)?0:1
if(e.reduxEvents){const t=a
let r=0
a=()=>t&&!t()?0:r,s=({detail:t})=>{e.reduxEvents.includes(t.action.type)&&(r=1)},this.redux.initialize(),this.redux.addEventListener("statechanged",s)}const u=scratchAddons.sharedObserver.watch({query:t,seen:r?this._waitForElementSet:null,condition:a,elementCondition:e.elementCondition||null})
return s&&u.then((t=>(this.redux.removeEventListener("statechanged",s),t))),u}get editorMode(){const t=location.pathname.toLowerCase().split("/").filter(Boolean)
return t[0]&&"projects"===t[0]?t.includes("editor")?"editor":t.includes("fullscreen")?"fullscreen":t.includes("embed")?"embed":"projectpage":null}copyImage(t){if(!t.startsWith("data:image/png;base64,"))return Promise.reject(new TypeError("Expected PNG data URL"))
if("function"==typeof Clipboard.prototype.write){const e=o(t),r=[new ClipboardItem({"image/png":e})]
return navigator.clipboard.write(r)}return scratchAddons.methods.copyImage(t).catch((t=>Promise.reject(new Error(`Error inside clipboard handler: ${t}`))))}scratchMessage(t){if("scratch-www"===this.clientVersion){if(this.editorMode&&this.redux.state&&this.redux.state.locales.messages[t])return this.redux.state.locales.messages[t]
const e=[window._locale?window._locale.toLowerCase():"en"]
e[0].includes("-")&&e.push(e[0].split("-")[0]),e.includes("pt")&&!e.includes("pt-br")&&e.push("pt-br"),e.includes("en")||e.push("en")
for(const r of e)if(window._messages[r]&&window._messages[r][t])return window._messages[r][t]
return console.warn("Unknown key: ",t),""}if("scratchr2"===this.clientVersion)return window.django.gettext(t)}get _eventTargetKey(){return"tab"}scratchClass(...t){let e=""
if(t.filter((t=>"string"==typeof t)).forEach((t=>{scratchAddons.classNames.loaded?e+=scratchAddons.classNames.arr.find((e=>e.startsWith(t+"_")&&e.length===t.length+6))||"":e+=`scratchAddonsScratchClass/${t}`,e+=" "})),"object"==typeof t[t.length-1]){const r=t[t.length-1];(Array.isArray(r.others)?r.others:[r.others]).forEach((t=>e+=t+" "))}return e=e.slice(0,-1),e=e.replace(/"/g,""),e}displayNoneWhileDisabled(t,{display:e=""}={}){t.style.display=`var(--${this._addonId.replace(/-([a-z])/g,(t=>t[1].toUpperCase()))}-_displayNoneWhileDisabledValue${e?", ":""}${e})`}get direction(){const t=scratchAddons.globalState.auth.scratchLang.split("-")[0]
return["ar","ckb","fa","he"].includes(t)?"rtl":"ltr"}appendToSharedSpace({space:t,element:e,order:r,scope:o}){const n=document.querySelector.bind(document),s={stageHeader:{element(){return n("[class^='stage-header_stage-size-row']")},from(){return[]},until(){return[n("[class^='stage-header_stage-size-toggle-group']"),n("[class^='stage-header_stage-size-row']").lastChild]}},fullscreenStageHeader:{element(){return n("[class^='stage-header_stage-menu-wrapper']")},from(){let t=this.element().querySelector(".sa-spacer")
return t||(t=document.createElement("div"),t.style.marginLeft="auto",t.className="sa-spacer",this.element().insertBefore(t,this.element().lastChild)),[t]},until(){return[n("[class^='stage-header_stage-menu-wrapper']").lastChild]}},afterGreenFlag:{element(){return n("[class^='controls_controls-container']")},from(){return[]},until(){return[n("[class^='stop-all_stop-all']")]}},afterStopButton:{element(){return n("[class^='controls_controls-container']")},from(){return[n("[class^='stop-all_stop-all']")]},until(){return[]}},beforeProjectActionButtons:{element(){return n(".flex-row.subactions > .flex-row.action-buttons")},from(){return[]},until(){return[n(".report-button"),n(".action-buttons > div")]}},afterCopyLinkButton:{element(){return n(".flex-row.subactions > .flex-row.action-buttons")},from(){return[n(".copy-link-button")]},until(){return[]}},afterSoundTab:{element(){return n("[class^='react-tabs_react-tabs__tab-list']")},from(){return[n("[class^='react-tabs_react-tabs__tab-list']").children[2]]},until(){return[n(".sa-find-bar")]}},forumsBeforePostReport:{element(){return o.querySelector(".postfootright > ul")},from(){return[]},until(){let t=o.querySelector(".postfootright > ul > li.postreport, .postfootright > ul > li.pseudopostreport")
return t||(t=Object.assign(document.createElement("li"),{className:"pseudopostreport",textContent:" 🞄 "}),this.element().appendChild(t)),[t]}},forumsAfterPostReport:{element(){return o.querySelector(".postfootright > ul")},from(){let t=o.querySelector(".postfootright > ul > li.postreport, .postfootright > ul > li.pseudopostreport")
return t||(t=Object.assign(document.createElement("li"),{className:"pseudopostreport",textContent:" 🞄 "}),this.element().appendChild(t)),[t]},until(){return[o.querySelector(".postfootright > ul > li.postquote")]}},beforeRemixButton:{element(){return n(".project-buttons")},from(){return[]},until(){return[n(".project-buttons > .remix-button:not(.sa-remix-button)"),n(".project-buttons > .see-inside-button")]}},studioCuratorsTab:{element(){return n(".studio-tabs div:nth-child(2)")},from(){return[]},until(){return[n(".studio-tabs div:nth-child(2) > .commenting-status"),n(".studio-tabs div:nth-child(2) > .studio-members")]}},forumToolbarTextDecoration:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton4")]},until(){return[n(".markItUpButton4 ~ .markItUpSeparator")]}},forumToolbarLinkDecoration:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton6")]},until(){return[n(".markItUpButton6 ~ .markItUpSeparator")]}},forumToolbarFont:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton7")]},until(){return[n(".markItUpButton7 ~ .markItUpSeparator")]}},forumToolbarList:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton10")]},until(){return[n(".markItUpButton10 ~ .markItUpSeparator")]}},forumToolbarDecoration:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton12")]},until(){return[n(".markItUpButton12 ~ .markItUpSeparator")]}},forumToolbarEnvironment:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton13")]},until(){return[n(".markItUpButton13 ~ .markItUpSeparator")]}},forumToolbarScratchblocks:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton14")]},until(){return[n(".markItUpButton14 ~ .markItUpSeparator")]}},forumToolbarTools:{element(){return n(".markItUpHeader > ul")},from(){return[n(".markItUpButton16")]},until(){return[]}},assetContextMenuAfterExport:{element(){return o},from:()=>[].filter.call(o.children,(t=>t.textContent===this.scratchMessage("gui.spriteSelectorItem.contextMenuExport"))),until:()=>[].filter.call(o.children,(t=>t.textContent===this.scratchMessage("gui.spriteSelectorItem.contextMenuDelete")))},assetContextMenuAfterDelete:{element(){return o},from:()=>[].filter.call(o.children,(t=>t.textContent===this.scratchMessage("gui.spriteSelectorItem.contextMenuDelete"))),until(){return[]}},monitor:{element(){return o},from:()=>{const t=[this.scratchMessage("gui.monitor.contextMenu.large"),this.scratchMessage("gui.monitor.contextMenu.slider"),this.scratchMessage("gui.monitor.contextMenu.sliderRange"),this.scratchMessage("gui.monitor.contextMenu.export")],e=[].filter.call(o.children,(e=>t.includes(e.textContent)))
return[e[e.length-1]]},until(){return[]}}}[t],a=s.element()
if(!a)return 0
const u=s.from(),i=s.until()
e.dataset.saSharedSpaceOrder=r
let l=0
0===u.length&&(l=1)
let c=null
const m=Array.from(a.children)
for(let t of m.keys()){const e=m[t],o=Number(t)
if(l){if(i.includes(e)){c=0===o?-1:m[o-1]
break}if(e.dataset.saSharedSpaceOrder&&Number(e.dataset.saSharedSpaceOrder)>r){c=0===o?-1:m[o-1]
break}}else u.includes(e)&&(l=1)}return l?("forumsBeforePostReport"===t?e.appendChild(document.createTextNode(" | ")):"forumsAfterPostReport"===t&&e.prepend(document.createTextNode("| ")),null===c?a.appendChild(e):-1===c?a.prepend(e):a.insertBefore(e,c.nextSibling),1):0}createBlockContextMenu(t,{workspace:e=0,blocks:r=0,flyout:o=0,comments:n=0}={}){u.push({addonId:this._addonId,callback:t,workspace:e,blocks:r,flyout:o,comments:n}),u.sort(((t,e)=>i.indexOf(t.addonId)-i.indexOf(e.addonId))),l||(l=1,this.traps.getBlockly().then((t=>{const e=t.ContextMenu.show
t.ContextMenu.show=function(r,o,n){const s=t.mainWorkspace.currentGesture_,a=s.targetBlock_
for(const{callback:t,workspace:e,blocks:r,flyout:n,comments:i}of u)if(e&&!a&&!s.flyout_&&!s.startBubble_||r&&a&&!s.flyout_||n&&s.flyout_||i&&s.startBubble_)try{o=t(o,a)}catch(t){console.error("Error while calling context menu callback: ",t)}e.call(this,r,o,n)
const i=t.WidgetDiv.DIV.firstChild
o.forEach(((t,e)=>{if(0!==e&&t.separator){const t=i.children[e]
t.style.paddingTop="2px",t.style.borderTop="1px solid hsla(0, 0%, 0%, 0.15)"}}))}})))}createEditorContextMenu(...t){s(this,...t)}createModal(t,{isOpen:e=0,useEditorClasses:r=0,useSizesClass:o=0}={}){return null!==this.editorMode&&r?a.createEditorModal(this,t,{isOpen:e}):"scratch-www"===this.clientVersion?a.createScratchWwwModal(t,{isOpen:e,useSizesClass:o}):a.createScratchr2Modal(t,{isOpen:e})}confirm(t,e,r){return a.confirm(this,t,e,r)}prompt(t,e,r,o){return a.prompt(this,t,e,r,o)}}