export default async function({addon:e,msg:t}){async function o(e){return(await fetch(`https://my-ocular.jeffalo.net/api/reactions/${e}`)).json()}let c=document.querySelectorAll(".blockpost")
const n=await e.auth.fetchIsLoggedIn(),a=await e.auth.fetchUsername()
for(const u of c){let r=u.id.split("p")[1],i=document.createElement("li")
e.tab.displayNoneWhileDisabled(i)
let m=document.createElement("a")
if(m.innerText="🔍 ocular",m.title=t("view-on-ocular"),m.href=`https://ocular.jeffalo.net/post/${r}`,i.appendChild(m),e.tab.appendToSharedSpace({space:"forumsBeforePostReport",scope:u,element:i,order:2}),n){let s=document.createElement("li")
e.tab.displayNoneWhileDisabled(s),s.className="my-ocular-reaction-menu"
let p=document.createElement("a")
p.href="",p.className="my-ocular-reaction-menu-button",p.innerText="😀",p.title=t("add-reaction"),s.appendChild(p)
let f=document.createElement("span")
f.className="my-ocular-popup",s.appendChild(f),p.addEventListener("click",(e=>{e.preventDefault(),e.stopPropagation(),s.classList.toggle("open")
for(let e of document.querySelectorAll(".my-ocular-reaction-menu"))e!==s&&e.classList.remove("open")})),document.body.addEventListener("click",(()=>s.classList.remove("open"))),f.addEventListener("click",(e=>e.stopPropagation()))
let d=document.createElement("li")
async function l(e,t){const c=await o(r)
d.innerHTML="",f.innerHTML="",c.forEach((o=>{function c(e,t){e.preventDefault()
let c=window.open(`https://ocular.jeffalo.net/react/${r}?emoji=${o.emoji}`,"ocular","width=300,height=300"),n=setInterval((function(){c.closed&&(clearInterval(n),l(o.emoji,t))}),500)}let n=0!==o.reactions.length?document.createElement("a"):null
if(n&&(n.href=""),n&&(n.className="my-ocular-reaction-button"),n&&(n.innerText=`${o.emoji} ${o.reactions.length}`),n&&o.emoji.startsWith(":")&&o.emoji.endsWith(":")){let e=`https://ocular.jeffalo.net/emojis/${o.emoji.slice(1,-1)}.png`,t=document.createElement("img")
t.src=e,n.innerText="",n.appendChild(t)
let c=document.createElement("span")
c.innerText=` ${o.reactions.length}`,n.appendChild(c)}let u=document.createElement("a")
if(u.href="",u.className="my-ocular-reaction-button",u.innerText=o.emoji,o.emoji.startsWith(":")&&o.emoji.endsWith(":")){let e=`https://ocular.jeffalo.net/emojis/${o.emoji.slice(1,-1)}.png`,t=document.createElement("img")
t.src=e,u.innerText="",u.appendChild(t)}if(o.reactions.find((e=>e.user===a))&&(n&&n.classList.add("selected"),u.classList.add("selected")),n){let e=document.createElement("span")
e.className="my-ocular-popup",e.innerText=o.reactions.length>5?o.reactions.slice(0,5).map((e=>e.user)).join(", ")+" and others":o.reactions.map((e=>e.user)).join(", "),n.appendChild(e)}n&&n.addEventListener("click",(e=>c(e,0))),u.addEventListener("click",(e=>c(e,1))),n&&d.appendChild(n),n&&e===o.emoji&&!t&&n.focus(),f.appendChild(u),e===o.emoji&&t&&u.focus()})),c.some((e=>0!==e.reactions.length))&&d.appendChild(document.createTextNode("| "))}e.tab.displayNoneWhileDisabled(d),e.tab.appendToSharedSpace({space:"forumsBeforePostReport",scope:u,element:s,order:1}),e.tab.appendToSharedSpace({space:"forumsBeforePostReport",scope:u,element:d,order:0}),await l()}}}