export default async function({addon:e,msg:o}){const t=e.settings.get("showMenu"),r=e.settings.get("forceAlternative"),a=e.settings.get("alternativePlayer"),n=e.settings.get("autoPlay"),c=e.settings.get("enableTWAddons"),l=await e.self.getEnabledAddons("editor"),s=document.querySelector(".stage"),u=window.Scratch.INIT_DATA.PROFILE.featuredProject.id,d=document.createElement("iframe")
d.setAttribute("allowtransparency",""),d.setAttribute("width","282"),d.setAttribute("height","210"),d.setAttribute("frameborder","0"),d.setAttribute("allowfullscreen",""),d.setAttribute("allow","autoplay 'src'; camera 'src'; document-domain 'none'; fullscreen 'src'; gamepad 'src'; microphone 'src';"),d.setAttribute("scrolling","no")
const i=document.createElement("div")
i.id="lfp-embed"
const h=document.createElement("div")
h.id="lfp-change-featured",h.textContent=o("change-featured"),h.addEventListener("click",(()=>{document.querySelector('#profile-box .player [data-control="edit"]').click()})),i.appendChild(d),document.querySelector('#profile-box .player [data-control="edit"]')&&i.appendChild(h),s.prepend(i),i.classList.add(t?"lfp-show-menu":"lfp-hide-menu")
const p=()=>{const e=new URLSearchParams
n&&e.set("autoplay",""),c&&e.set("addons",l.join(",")),d.setAttribute("src",`https://turbowarp.org/${u}/embed?${e}`),i.dataset.player="turbowarp",t||d.setAttribute("height","260")},f=()=>{i.dataset.player="forkphorus",d.setAttribute("src",`https://forkphorus.github.io/embed.html?id=${u}&auto-start=${n}&ui=${t}`)}
r&&"none"!==a?"turbowarp"===a?p():"forkphorus"===a&&f():(i.dataset.player="scratch",t||d.setAttribute("height","260"),d.setAttribute("src",`https://scratch.mit.edu/projects/embed/${u}/?autostart=true`),n&&d.addEventListener("load",(function(){const e=new MutationObserver((()=>{null===d.contentDocument.querySelector("[class^='loader_fullscreen']")&&(d.contentDocument.querySelector("[class^='green-flag_green-flag']").click(),e.disconnect())}))
e.observe(d.contentDocument.body,{childList:1,subtree:1})}),{once:1}),d.addEventListener("load",(()=>{null!==d.contentDocument.querySelector(".not-available-outer")&&("turbowarp"===a?p():"forkphorus"===a?f():s.removeChild(i))})))}