name: Build source code for production
on:
  workflow_dispatch:
  push:
    branches: userscript

jobs:
  run:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.JS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: Install
        run: npm install terser@5.15.1 posthtml-cli@0.10.0 postcss-cli@10.0.0 posthtml-postcss@0.5.0 htmlnano@2.0.2 cssnano@5.1.0 autoprefixer@10.4.12

      - name: Terser
        run: node .github/workflows/minify/terser.mjs

      - name: JSON.stringify
        run: node .github/workflows/minify/json.mjs

      - name: Bundle
        run: node .github/workflows/minify/bundle.mjs

      - name: PostCSS
        run: npx postcss-cli -r --env="production" "**.css"

      - name: PostHTML
        run: npx posthtml-cli "**/*.html" -c .posthtmlrc.js

      - name: CNAME
        run: echo "sa-userscript-dev.cf" >> CNAME

      - name: Jekyll
        run: echo "" >> .nojekyll

      - name: Commit
        run: |
          git config user.email "RedGuy12@users.noreply.github.com"
          git config user.name "RedGuy12"
          git commit -am "Update prerelease version";
          git fetch
          git push origin HEAD:release --force;
