name: ESLint

on: [push, pull_request]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.json
          --ext .js
        continue-on-error: true
