name: Minify source code for production
on:
  workflow_dispatch:
  push:
    branches: userscript

jobs:
  run:
    name: Minify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - name: Install
        run: npm install terser@5.9.0 posthtml-cli@0.10.0 postcss-cli@9.0.1 posthtml-postcss@0.5.0 htmlnano@1.1.1 postcss-import@14.0.2 cssnano@5.0.8 autoprefixer@10.3.6

      - name: Terser
        run: node .github/workflows/minify/terser.mjs

      - name: JSON.stringify
        run: node .github/workflows/minify/json.mjs

      - name: Bundle
        run: node .github/workflows/minify/bundle.mjs

      - name: PostCSS
        run: npx postcss-cli -r --env="production" "**.css"

      - name: PostHTML
        run: npx posthtml-cli "**/*.html" -c .posthtmlrc.js

      - name: Commit
        run: |
          git config user.email "RedGuy12@users.noreply.github.com"
          git config user.name "RedGuy12"
          git commit -am "Update prerelease version";
          git fetch
          git push origin HEAD:release --force;
